version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      routine-npm-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: pip
    directory: /backend
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      routine-pip-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      routine-actions-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
