"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2 and maintained for Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from email.utils import parseaddr
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured


def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(
        f"{name} must be one of: true, false, 1, 0, yes, no, on, off."
    )


def env_csv(name, default=()):
    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment and security configuration

COMMERCE_ENV = os.environ.get("COMMERCE_ENV", "").strip().lower()
if not COMMERCE_ENV:
    raise ImproperlyConfigured(
        "COMMERCE_ENV must be explicitly set to 'development' or 'production'."
    )
if COMMERCE_ENV not in {"development", "production"}:
    raise ImproperlyConfigured(
        "COMMERCE_ENV must be either 'development' or 'production'."
    )

IS_PRODUCTION = COMMERCE_ENV == "production"

if IS_PRODUCTION:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
    if (
        len(SECRET_KEY) < 50
        or len(set(SECRET_KEY)) < 5
        or SECRET_KEY.startswith("django-insecure-")
        or "changeme" in SECRET_KEY.lower()
    ):
        raise ImproperlyConfigured(
            "Production requires a strong DJANGO_SECRET_KEY of at least 50 "
            "characters and sufficient diversity; development keys and "
            "placeholders are rejected."
        )

    if env_bool("DJANGO_DEBUG", False):
        raise ImproperlyConfigured("DJANGO_DEBUG cannot be enabled in production.")
    DEBUG = False

    ALLOWED_HOSTS = env_csv("DJANGO_ALLOWED_HOSTS")
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "Production requires DJANGO_ALLOWED_HOSTS with at least one hostname."
        )
    if "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "Production DJANGO_ALLOWED_HOSTS cannot contain the wildcard '*'."
        )
    development_hosts = {"localhost", "127.0.0.1", "[::1]", "web", "testserver"}
    if not set(ALLOWED_HOSTS) - development_hosts:
        raise ImproperlyConfigured(
            "Production DJANGO_ALLOWED_HOSTS must include a deployment hostname."
        )
else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
    if not SECRET_KEY:
        raise ImproperlyConfigured(
            "Development requires DJANGO_SECRET_KEY; the local Compose "
            "workflow supplies a labeled development-only value."
        )
    DEBUG = env_bool("DJANGO_DEBUG", True)
    ALLOWED_HOSTS = env_csv(
        "DJANGO_ALLOWED_HOSTS",
        ("localhost", "127.0.0.1", "[::1]", "web", "testserver"),
    )

CSRF_TRUSTED_ORIGINS = env_csv("DJANGO_CSRF_TRUSTED_ORIGINS")

SESSION_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", IS_PRODUCTION)
SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

TRUST_FORWARDED_PROTO = env_bool("DJANGO_TRUST_FORWARDED_PROTO", False)
if TRUST_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REFRESH_COOKIE_SECURE = IS_PRODUCTION
REFRESH_COOKIE_HTTPONLY = True
REFRESH_COOKIE_SAMESITE = "Strict"
REFRESH_COOKIE_PATH = "/api/auth/"

AUTH_REQUIRE_VERIFIED_EMAIL = env_bool("AUTH_REQUIRE_VERIFIED_EMAIL", False)
AUTH_EMAIL_VERIFICATION_TTL_SECONDS = env_int(
    "AUTH_EMAIL_VERIFICATION_TTL_SECONDS",
    86400,
)
AUTH_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = env_int(
    "AUTH_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS",
    60,
)
AUTH_PASSWORD_RECOVERY_TTL_SECONDS = env_int(
    "AUTH_PASSWORD_RECOVERY_TTL_SECONDS",
    1800,
)
AUTH_PASSWORD_RECOVERY_RESEND_COOLDOWN_SECONDS = env_int(
    "AUTH_PASSWORD_RECOVERY_RESEND_COOLDOWN_SECONDS",
    60,
)
AUTH_FRONTEND_BASE_URL = os.environ.get(
    "AUTH_FRONTEND_BASE_URL",
    "http://localhost:5173" if not IS_PRODUCTION else "",
).strip().rstrip("/")
EMAIL_BACKEND_NAME = os.environ.get(
    "EMAIL_BACKEND",
    (
        "accounts.mail.ReadableConsoleEmailBackend"
        if not IS_PRODUCTION
        else ""
    ),
).strip()
SMTP_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Commerce Architect <noreply@localhost>" if not IS_PRODUCTION else "",
).strip()

MAILER_OPTIONS = {}
if EMAIL_BACKEND_NAME == SMTP_BACKEND:
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_username = os.environ.get("SMTP_USERNAME", "").strip()
    smtp_password = os.environ.get("SMTP_PASSWORD", "")
    smtp_port = env_int("SMTP_PORT", 587)
    smtp_use_tls = env_bool("SMTP_USE_TLS", True)
    smtp_use_ssl = env_bool("SMTP_USE_SSL", False)
    smtp_timeout = env_int("SMTP_TIMEOUT", 10)

    missing_smtp_variables = [
        name
        for name, value in (
            ("SMTP_HOST", smtp_host),
            ("SMTP_USERNAME", smtp_username),
            ("SMTP_PASSWORD", smtp_password),
        )
        if not value
    ]
    if missing_smtp_variables:
        raise ImproperlyConfigured(
            "SMTP email requires configuration: "
            + ", ".join(missing_smtp_variables)
        )
    if not 1 <= smtp_port <= 65535:
        raise ImproperlyConfigured("SMTP_PORT must be between 1 and 65535.")
    if smtp_use_tls and smtp_use_ssl:
        raise ImproperlyConfigured(
            "SMTP_USE_TLS and SMTP_USE_SSL cannot both be enabled."
        )
    if smtp_timeout <= 0:
        raise ImproperlyConfigured("SMTP_TIMEOUT must be positive.")

    MAILER_OPTIONS = {
        "host": smtp_host,
        "port": smtp_port,
        "username": smtp_username,
        "password": smtp_password,
        "use_tls": smtp_use_tls,
        "use_ssl": smtp_use_ssl,
        "timeout": smtp_timeout,
    }

if AUTH_EMAIL_VERIFICATION_TTL_SECONDS <= 0:
    raise ImproperlyConfigured("AUTH_EMAIL_VERIFICATION_TTL_SECONDS must be positive.")
if AUTH_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS < 0:
    raise ImproperlyConfigured(
        "AUTH_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS cannot be negative."
    )
if AUTH_PASSWORD_RECOVERY_TTL_SECONDS <= 0:
    raise ImproperlyConfigured("AUTH_PASSWORD_RECOVERY_TTL_SECONDS must be positive.")
if AUTH_PASSWORD_RECOVERY_RESEND_COOLDOWN_SECONDS < 0:
    raise ImproperlyConfigured(
        "AUTH_PASSWORD_RECOVERY_RESEND_COOLDOWN_SECONDS cannot be negative."
    )

if IS_PRODUCTION:
    frontend_url = urlparse(AUTH_FRONTEND_BASE_URL)
    unsafe_email_backends = {
        "",
        "django.core.mail.backends.console.EmailBackend",
        "accounts.mail.ReadableConsoleEmailBackend",
        "django.core.mail.backends.dummy.EmailBackend",
        "django.core.mail.backends.locmem.EmailBackend",
    }
    if frontend_url.scheme != "https" or not frontend_url.netloc:
        raise ImproperlyConfigured(
            "Production requires AUTH_FRONTEND_BASE_URL to be an absolute HTTPS URL."
        )
    if EMAIL_BACKEND_NAME in unsafe_email_backends:
        raise ImproperlyConfigured(
            "Production requires an explicit delivery-capable EMAIL_BACKEND."
        )
    sender_address = parseaddr(DEFAULT_FROM_EMAIL)[1].casefold()
    if not sender_address or sender_address.endswith("@localhost"):
        raise ImproperlyConfigured(
            "Production requires an explicit non-local DEFAULT_FROM_EMAIL."
        )

MAILERS = {
    "default": {
        "BACKEND": EMAIL_BACKEND_NAME,
        "OPTIONS": MAILER_OPTIONS,
    }
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'catalog',
]

STATICFILES_DIRS = [
        BASE_DIR / "static",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if IS_PRODUCTION:
    missing_database_variables = [
        name
        for name in (
            "DATABASE_HOST",
            "DATABASE_NAME",
            "DATABASE_USER",
            "DATABASE_PASSWORD",
        )
        if not os.environ.get(name, "").strip()
    ]
    if missing_database_variables:
        raise ImproperlyConfigured(
            "Production requires database configuration: "
            + ", ".join(missing_database_variables)
        )
    if os.environ["DATABASE_PASSWORD"] in {"commercepass", "changeme"}:
        raise ImproperlyConfigured(
            "Production rejects the known development DATABASE_PASSWORD."
        )

DATABASES = {
    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME"),
        "USER": os.environ.get("DATABASE_USER"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
        "HOST": os.environ.get("DATABASE_HOST"),
        "PORT": os.environ.get("DATABASE_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "password_recovery_request": "5/minute",
    },
    # Trust one forwarding hop only when the deployment explicitly trusts the
    # platform proxy for the original HTTPS scheme; local clients use REMOTE_ADDR.
    "NUM_PROXIES": 1 if TRUST_FORWARDED_PROTO else 0,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}
