
services:
  db:
    image: docker.io/library/postgres:16
    container_name: commerce_db
    restart: always
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commercepass
      POSTGRES_DB: commerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: commerce_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: commerce_db
      DATABASE_USER: commerce
      DATABASE_PASSWORD: commercepass

volumes:
  postgres_data:
